version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/aliendb

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install codacy-coverage

      - run:
          name: setup environment
          command: |
            docker-compose build
            docker-compose up -d

      - run:
          name: run tests
          command: |
            docker exec -it aliendb_web_1 coverage run --source='.' manage.py test aliendb.apps.analytics.tests --noinput
            docker exec -it aliendb_web_1 coverage xml
            docker exec -it aliendb_web_1 cat coverage.xml > coverage.xml
            sed -i -e "s@/usr/src/app@$(pwd)/web@g" coverage.xml

      - run:
          name: upload codacy coverage
          command: |
            . venv/bin/activate
            python-codacy-coverage -r coverage.xml